#!/bin/bash
npm run test:balance
npm run test:custom-task
npm run test:anticloudflare
npm run test:antiturnstile  
npm run test:antiturnstileproxyless
npm run test:datadome
npm run test:img2txt
npm run test:mtcaptcha
npm run test:funcaptchaclassification
npm run test:funcaptcha
npm run test:funcaptchaproxyless
npm run test:geetestv3
npm run test:geetestv3proxyless
npm run test:geetestv4
npm run test:geetestv4proxyless
npm run test:hcaptcha
npm run test:hcaptchaclassification
npm run test:hcaptchaproxyless
npm run test:recatpchav2
npm run test:recatpchav2proxyless
npm run test:recatpchav3
npm run test:recatpchav3proxyless
